Script started on Wed 04 Nov 2015 10:47:03 PM PST
jliaw001@hammer:~/cs100/assignments/assignment1
[jliaw001@hammer assignment1]$ bin/rshell
[jliaw001@hammer.cs.ucr.edu]$ echo hello world #echo I'm a comment
hello world
[jliaw001@hammer.cs.ucr.edu]$ echo more comments #sdfaweiuhfasopifjaweofijsgpuahewf09234udf #0a9fw3ifjdoaig
more comments
[jliaw001@hammer.cs.ucr.edu]$ ls -a
.  ..  bin  .git  LICENSE  makefile  README.md	src  tests
[jliaw001@hammer.cs.ucr.edu]$ ls #-a
bin  LICENSE  makefile	README.md  src	tests
[jliaw001@hammer.cs.ucr.edu]$ #ls -a
[jliaw001@hammer.cs.ucr.edu]$ exit
jliaw001@hammer:~/cs100/assignments/assignment1
[jliaw001@hammer assignment1]$ exit
exit

Script done on Wed 04 Nov 2015 10:48:03 PM PST
