Script started on Wed 04 Nov 2015 10:28:46 PM PST
jliaw001@hammer:~/cs100/assignments/assignments
[jliaw001@hammer assignment1]$ bin/rshell
[jliaw001@hammer.cs.ucr.edu]$ ls
bin  LICENSE  makefile	README.md  src	tests
[jliaw001@hammer.cs.ucr.edu]$ ls -a
.  ..  bin  .git  LICENSE  makefile  README.md	src  tests
[jliaw001@hammer.cs.ucr.edu]$ echo hello
hello
[jliaw001@hammer.cs.ucr.edu]$ echo hello world
hello world
[jliaw001@hammer.cs.ucr.edu]$  echo hello
execvp failed: No such file or directory
[jliaw001@hammer.cs.ucr.edu]$ exit
jliaw001@hammer:~/cs100/assignments/assignment1
[jliaw001@hammer assignment1]$ exit
exit

Script done on Wed 04 Nov 2015 10:29:23 PM PST
